// File generated from our OpenAPI spec
namespace Stripe
{
    using System.Text.Json.Serialization;
    using Stripe.Infrastructure;

    public class SetupAttemptPaymentMethodDetailsCardPresent : StripeEntity<SetupAttemptPaymentMethodDetailsCardPresent>
    {
        #region Expandable GeneratedCard

        /// <summary>
        /// (ID of the PaymentMethod)
        /// The ID of the Card PaymentMethod which was generated by this SetupAttempt.
        /// </summary>
        [JsonIgnore]
        public string GeneratedCardId
        {
            get => this.InternalGeneratedCard?.Id;
            set => this.InternalGeneratedCard = SetExpandableFieldId(value, this.InternalGeneratedCard);
        }

        /// <summary>
        /// (Expanded)
        /// The ID of the Card PaymentMethod which was generated by this SetupAttempt.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        public PaymentMethod GeneratedCard
        {
            get => this.InternalGeneratedCard?.ExpandedObject;
            set => this.InternalGeneratedCard = SetExpandableFieldObject(value, this.InternalGeneratedCard);
        }

        [JsonPropertyName("generated_card")]
        [JsonConverter(typeof(ExpandableFieldConverter<PaymentMethod>))]
        internal ExpandableField<PaymentMethod> InternalGeneratedCard { get; set; }
        #endregion
    }
}
