// File generated from our OpenAPI spec
namespace Stripe
{
    using System.Text.Json.Serialization;

    public class ChargePaymentMethodDetailsGrabpay : StripeEntity<ChargePaymentMethodDetailsGrabpay>
    {
        /// <summary>
        /// Unique transaction id generated by GrabPay.
        /// </summary>
        [JsonPropertyName("transaction_id")]
        public string TransactionId { get; set; }
    }
}
