// File generated from our OpenAPI spec
namespace Stripe
{
    using System.Text.Json.Serialization;

    public class ChargePaymentMethodDetailsPromptpay : StripeEntity<ChargePaymentMethodDetailsPromptpay>
    {
        /// <summary>
        /// Bill reference generated by PromptPay.
        /// </summary>
        [JsonPropertyName("reference")]
        public string Reference { get; set; }
    }
}
