// File generated from our OpenAPI spec
namespace Stripe
{
    using System.Text.Json.Serialization;

    public class SubscriptionScheduleDefaultSettingsAutomaticTaxOptions : INestedOptions
    {
        /// <summary>
        /// Enabled automatic tax calculation which will automatically compute tax rates on all
        /// invoices generated by the subscription.
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }
    }
}
