// File generated from our OpenAPI spec
namespace Stripe.Terminal
{
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public class ReaderCreateOptions : BaseOptions, IHasMetadata
    {
        /// <summary>
        /// Custom label given to the reader for easier identification. If no label is specified,
        /// the registration code will be used.
        /// </summary>
        [JsonPropertyName("label")]
        public string Label { get; set; }

        /// <summary>
        /// The location to assign the reader to.
        /// </summary>
        [JsonPropertyName("location")]
        public string Location { get; set; }

        /// <summary>
        /// Set of <a href="https://stripe.com/docs/api/metadata">key-value pairs</a> that you can
        /// attach to an object. This can be useful for storing additional information about the
        /// object in a structured format. Individual keys can be unset by posting an empty value to
        /// them. All keys can be unset by posting an empty value to <c>metadata</c>.
        /// </summary>
        [JsonPropertyName("metadata")]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// A code generated by the reader used for registering to an account.
        /// </summary>
        [JsonPropertyName("registration_code")]
        public string RegistrationCode { get; set; }
    }
}
